name: Prebuild

on:
  push:
    branches: [ prebuild ]

jobs:
  prebuild:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, windows-2022]

    steps:
    - if: matrix.os == 'windows-2022'
      name: Configure MSVC (Windows)
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Meson and Ninja
      run: |
        pip3 install --upgrade meson ninja

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build OpenSSL
      run: |
        cd openssl
        meson setup builddir --buildtype=release -Dmt=enabled
        meson compile -C builddir

    - if: matrix.os == 'macos-11'
      name: Build Poco (MacOS)
      run: |
        mkdir -p builddir
        cd builddir
        cp -r ../openssl/subprojects/openssl-3.0.2/generated-config/archs/darwin64-x86_64-cc/asm/include ../openssl/subprojects/openssl-3.0.2
        cmake .. -DCMAKE_INSTALL_PREFIX=bundle -DENABLE_CRYPTO=ON -DBUILD_SHARED_LIBS=OFF -DOPENSSL_INCLUDE_DIR=./openssl/subprojects/openssl-3.0.2/include -DOPENSSL_CRYPTO_LIBRARY=./openssl/builddir/subprojects/openssl-3.0.2/libcrypto.a -DOPENSSL_SSL_LIBRARY=./openssl/builddir/subprojects/openssl-3.0.2/libssl.a
        cmake --build . --config Release -- -j8
        cmake --build . --target install

    - if: matrix.os == 'windows-2022'
      name: Build Poco /MT (Windows)
      run: |
        mkdir -force builddir
        cd builddir
        cp -r -force ../openssl/subprojects/openssl-3.0.2/generated-config/archs/VC-WIN64A/no-asm/include ../openssl/subprojects/openssl-3.0.2
        cmake .. -DCMAKE_INSTALL_PREFIX=bundle -DENABLE_CRYPTO=ON -DBUILD_SHARED_LIBS=OFF -DPOCO_MT=ON -DOPENSSL_INCLUDE_DIR=../openssl/subprojects/openssl-3.0.2/include -DOPENSSL_CRYPTO_LIBRARY=../openssl/builddir/subprojects/openssl-3.0.2/libcrypto.a -DOPENSSL_SSL_LIBRARY=../openssl/builddir/subprojects/openssl-3.0.2/libssl.a
        cmake --build . --config Release
        cmake --build . --target install

    - name: Bundle
      run: |
        python3 ./scripts/bundle.py builddir/bundle

    - name: Upload
      uses: ncipollo/release-action@v1.10.0
      with:
        allowUpdates: true
        replacesArtifacts: true
        tag: build-${{ github.run_number }}
        name: Build ${{ github.run_number }}
        artifacts: builddir/Poco*.zip
        artifactContentType: application/zip
        commit: ${{ github.sha }}
