name: Prebuild

on:
  push:
    branches: [ prebuild ]

jobs:
  prebuild:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, windows-2022]

    steps:
    - if: matrix.os == 'windows-2022'
      name: Configure MSVC (Windows)
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Meson and Ninja
      run: |
        pip3 install --upgrade meson ninja

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - if: matrix.os == 'macos-11'
      name: Build - Release (MacOS)
      run: |
        cd openssl
        meson setup builddir --buildtype=release
        meson compile -C builddir
        cd ..
        mkdir -p builddir
        cd builddir
        cp -r ../openssl/subprojects/openssl-3.0.2/generated-config/archs/darwin64-x86_64-cc/asm/include ../openssl/subprojects/openssl-3.0.2
        cmake .. -DCMAKE_INSTALL_PREFIX=bundle -DENABLE_CRYPTO=ON -DBUILD_SHARED_LIBS=OFF
        cmake --build . --config Release -- -j8
        cmake --build . --target install
        python3 ../scripts/bundle.py release

    - if: matrix.os == 'macos-11'
      name: Build - Debug (MacOS)
      run: |
        rm -r builddir
        rm -r openssl/builddir

        cd openssl
        meson setup builddir --buildtype=debug
        meson compile -C builddir
        cd ..
        mkdir -p builddir
        cd builddir
        cp -r ../openssl/subprojects/openssl-3.0.2/generated-config/archs/darwin64-x86_64-cc/asm/include ../openssl/subprojects/openssl-3.0.2
        cmake .. -DCMAKE_INSTALL_PREFIX=bundle -DENABLE_CRYPTO=ON -DBUILD_SHARED_LIBS=OFF
        cmake --build . --config Debug -- -j8
        cmake --build . --target install
        python3 ../scripts/bundle.py debug

    - if: matrix.os == 'windows-2022'
      name: Build - Release /MT (Windows)
      run: |
        cd openssl
        meson setup builddir --buildtype=release -Dmt=enabled
        meson compile -C builddir
        cd ..
        mkdir -force builddir
        cd builddir
        cp -r -force ../openssl/subprojects/openssl-3.0.2/generated-config/archs/VC-WIN64A/no-asm/include ../openssl/subprojects/openssl-3.0.2
        cmake .. -DCMAKE_INSTALL_PREFIX=bundle -DENABLE_CRYPTO=ON -DBUILD_SHARED_LIBS=OFF -DPOCO_MT=ON
        cmake --build . --config Release
        cmake --build . --target install
        python3 ../scripts/bundle.py release_mt

    - if: matrix.os == 'windows-2022'
      name: Build - Release /MD (Windows)
      run: |
        rm -r builddir
        rm -r openssl/builddir

        cd openssl
        meson setup builddir --buildtype=release -Dmt=disabled
        meson compile -C builddir
        cd ..
        mkdir -force builddir
        cd builddir
        cp -r -force ../openssl/subprojects/openssl-3.0.2/generated-config/archs/VC-WIN64A/no-asm/include ../openssl/subprojects/openssl-3.0.2
        cmake .. -DCMAKE_INSTALL_PREFIX=bundle -DENABLE_CRYPTO=ON -DBUILD_SHARED_LIBS=OFF -DPOCO_MT=OFF
        cmake --build . --config Release
        cmake --build . --target install
        python3 ../scripts/bundle.py release_md

    - if: matrix.os == 'windows-2022'
      name: Build - Debug /MT (Windows)
      run: |
        rm -r builddir
        rm -r openssl/builddir

        cd openssl
        meson setup builddir --buildtype=debug -Dmt=enabled
        meson compile -C builddir
        cd ..
        mkdir -force builddir
        cd builddir
        cp -r -force ../openssl/subprojects/openssl-3.0.2/generated-config/archs/VC-WIN64A/no-asm/include ../openssl/subprojects/openssl-3.0.2
        cmake .. -DCMAKE_INSTALL_PREFIX=bundle -DENABLE_CRYPTO=ON -DBUILD_SHARED_LIBS=OFF -DPOCO_MT=ON
        cmake --build . --config Debug
        cmake --build . --target install
        python3 ../scripts/bundle.py debug_mt

    - if: matrix.os == 'windows-2022'
      name: Build - Debug /MD (Windows)
      run: |
        rm -r builddir
        rm -r openssl/builddir

        cd openssl
        meson setup builddir --buildtype=debug -Dmt=disabled
        meson compile -C builddir
        cd ..
        mkdir -force builddir
        cd builddir
        cp -r -force ../openssl/subprojects/openssl-3.0.2/generated-config/archs/VC-WIN64A/no-asm/include ../openssl/subprojects/openssl-3.0.2
        cmake .. -DCMAKE_INSTALL_PREFIX=bundle -DENABLE_CRYPTO=ON -DBUILD_SHARED_LIBS=OFF -DPOCO_MT=OFF
        cmake --build . --config Debug
        cmake --build . --target install
        python3 ../scripts/bundle.py debug_md done

    - name: Upload
      uses: ncipollo/release-action@v1.10.0
      with:
        allowUpdates: true
        replacesArtifacts: true
        tag: build-${{ github.run_number }}
        name: Build ${{ github.run_number }}
        artifacts: scripts/Poco*.zip
        artifactContentType: application/zip
        commit: ${{ github.sha }}
